language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
addons:
  sonarqube:
    organization: "tschesky-github" # the key of the org you chose at step #3
script:
 - sonar-scanner
after_success:
  - coveralls