# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagues',
            options={},
        ),
        migrations.AlterModelOptions(
            name='learningvectors',
            options={},
        ),
        migrations.AlterModelOptions(
            name='matches',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={},
        ),
    ]
