# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 12:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_content', '0002_auto_20171202_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='cart_proba',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=3),
        ),
        migrations.AddField(
            model_name='matches',
            name='nb_proba',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=3),
        ),
        migrations.AddField(
            model_name='matches',
            name='svm_proba',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=3),
        ),
    ]
